### ISSUE TITLE
nonwhitespace character at 490

### ISSUE THREAD

**Issue by Technical-Analytics-Implementation** [google/google-analytics-utilities#9] opened 2023-02-14 21:35 UTC
Hi there! 

We are using this utility to try to automate creation of **Audiences** but there is an error ```nonwhitespace character at 490.```

In the JSON we have an **EXCLUDE** _clausetype_ and the initial thought is that there is a limitation when using **EXCLUDE**.

After checking the docs and not finding any resolution, I think this might be expected behavior when **EXCLUDING** Audiences but I wanted to check here by filing an issue. 

Does this utility work when **EXCLUDING** Audiences? 

Thank you. 

_`See JSON below`_

```
{
    "clauseType": "INCLUDE",
    "simpleFilter":
    {
        "scope": "AUDIENCE_FILTER_SCOPE_WITHIN_SAME_SESSION",
        "filterExpression":
        {
            "andGroup":
            {
                "filterExpressions": [
                {
                    "orGroup":
                    {
                        "filterExpressions": [
                        {
                            "dimensionOrMetricFilter":
                            {
                                "fieldName": "unifiedPagePathScreen",
                                "stringFilter":
                                {
                                    "value": "verterra",
                                    "matchType": "CONTAINS"                                },
                                "atAnyPointInTime": true                            }
                        },
                        {
                            "dimensionOrMetricFilter":
                            {
                                "fieldName": "unifiedPagePathScreen",
                                "stringFilter":
                                {
                                    "matchType": "CONTAINS",
                                    "value": "/events/alc-tvr"                                },
                                "atAnyPointInTime": true                            }
                        }]
                    }
                }]
            }
        }
    }
},
{
    "simpleFilter":
    {
        "scope": "AUDIENCE_FILTER_SCOPE_ACROSS_ALL_SESSIONS",
        "filterExpression":
        {
            "andGroup":
            {
                "filterExpressions": [
                {
                    "orGroup":
                    {
                        "filterExpressions": [
                        {
                            "dimensionOrMetricFilter":
                            {
                                "atAnyPointInTime": true,
                                "stringFilter":
                                {
                                    "matchType": "CONTAINS",
                                    "value": "form complete"                                },
                                "fieldName": "event_action"                            }
                        },
                        {
                            "dimensionOrMetricFilter":
                            {
                                "fieldName": "unifiedPagePathScreen",
                                "stringFilter":
                                {
                                    "value": "/investor",
                                    "matchType": "CONTAINS"                                },
                                "atAnyPointInTime": true                            }
                        }]
                    }
                }]
            }
        }
    },
    "clauseType": "EXCLUDE"}
```

**Comment by b-kuehn** [comment] 2023-02-17 14:35
Thanks for reporting this! This isn't intended behavior. I'll investigate this to see exactly what might be causing the problem and how to fix the script.

**Comment by Technical-Analytics-Implementation** [comment] 2023-02-24 17:58
That would be great! Thank you for the quick response.

**Comment by b-kuehn** [comment] 2023-07-17 16:19
This issue has been fixed in the template property and will be pushed to GitHub soon.

**Closed by b-kuehn** 2023-07-17 16:19 UTC
